### ISSUE TITLE
Question about catch-all aliases

### ISSUE THREAD

**Issue by aellwein** [albertito/chasquid#23]
Hi,

i have a question about configuration. 

For instance, i've already got "foo@mydomain" and "bar@mydomain" addresses defined in my configuration for some specific users, but i want to have a "catch all" rule, which catches mails sent to unresolvable user (e.g. "unknown@mydomain") and delivers them to some configured user (like, mine)?
 
Is that possible to configure such kind of "catch all" rule for aliases?

**Comment by aellwein** [comment]
@albertito if you find time, the pull request contains basic implementation. I'd be happy if you could review it.

**Comment by albertito** [comment]
Of course, thanks a lot for the patch! Sorry I've been slow to review, I came back earlier this week but it's been difficult to find the time for it. I will review the patch this weekend.

Thanks again!

**Comment by albertito** [comment]
Just FYI, and for discoverability: discussion about catch-all is pretty much happening on the pull request #24 .

I'll put a summary here later for reference, but for now let's centralize the discussion in #24 :)

**Comment by albertito** [comment]
This is now implemented in the `next` branch, commit f303e43 (it might be rebased in the future).

I'll leave it there for now so it gets more exposure and testing, and then move it to `master` for inclusion in the next release. I'll leave this issue open until then.

In the meantime, please comment further if you have any suggestions or ideas regarding this feature.

Thanks a lot!

**Comment by albertito** [comment]
The patch for catch-all aliases is now in the `master` branch, and will be included in the next release.

Thanks again!
