### ISSUE TITLE
Send-only server without dovecot?

### ISSUE THREAD

**Issue by usrtax** [albertito/chasquid#30]
I use gmail for receive emails, I just want run a self-host smtp server that I can send emails without limit

I've already configured spf with my own server's ip address

```
  ❯ nslookup -type=txt  _spf.user.tax
  _spf.user.tax   text = "v=spf1 ip4:62.171.170.189 ip6:2a02:c207:2098:9386::1 ~all"

  ❯ nslookup -type=txt  user.tax
  user.tax        text = "forward-email=i.user.tax@gmail.com"
  user.tax        text = "v=spf1 a mx include:_spf.user.tax include:_spf.google.com include:spf.forwardemail.net ~all"
```

My question now is how to run chasquid without dovecot? 

Is there any tutorial or example code  like this [How To Install and Configure Postfix as a Send-Only SMTP Server on Ubuntu 22.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-22-04)

Because I think I don't need to use dovecot.

**Comment by albertito** [comment]
If you don't need your server to store emails locally, like in your case where you only want to send, you don't need dovecot.

To set this up, you can [follow the how-to guide](https://blitiri.com.ar/p/chasquid/howto/), and just skip the Dovecot section.
For example, naming your server `sender.user.tax`.

Then, use [`chasquid-util
user-add me@user.tax `](https://manpages.debian.org/unstable/chasquid/chasquid-util.1.en.html#user-add) to add the users you'll use to send email.

And finally, add [aliases](https://blitiri.com.ar/p/chasquid/aliases/) to redirect incoming email to those users to the correct location. This should only be needed if you send emails to yourself, but can be convenient.

On your client, get them to use the server `sender.user.tax`, with user `me@user.tax` (including the domain is important, it has to match what you used in `chsquid-util` above).

I hope this helps!

**Comment by usrtax** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/110233389/192756242-0b4ed17f-fbf7-45c5-aec8-a8b20556f2a4.png">

see the image above , I tryed add user , but `535 5.7.8 Incorrect user or password`

I use `chasquid-util authenticate i@user.tax --password=CEQGzVgLTdZ2xfpg`
it output Authentication succeeded

I tryed systemctl restart chasquid   , still can't login

I use the default config without any change ( only add user  and setup ssl certificates )

**Comment by usrtax** [comment]
It works , thanks
