### ISSUE TITLE
[smtp-check]: Some MTA do reject client connections unless the local name looks like an fqdn

### ISSUE THREAD

**Issue by znerol** [albertito/chasquid#37]
The golang `net/smtp` package defaults to `localhost` for the `EHLO` local name unless specified otherwise using the [c.Hello](https://pkg.go.dev/net/smtp#Client.Hello) func.

Some MTA do reject client connections unless the local name at least looks like an fqdn. Extract from a sample run:

```
2023/07/14 16:08:19 === MX: 10  [...].
2023/07/14 16:08:19 SPF pass for [...]: matched ip
2023/07/14 16:08:24 TLS error: 550 Server name localhost is not a FQDN.
Please contact your ISP or system adminstrator.
2023/07/14 16:08:24 Allowed by policy
```

**Comment by albertito** [comment]
Thanks a lot for sending this!

It looks good to me. I merged it to the `next` branch, with some minor amends:

- Minor edits to the commit message (just editorial, e.g. "MTA" -> "MTAs").
- Ran `go fmt`.
- Renamed flag `--local_name` -> `--localname` for consistency with most other flags.

Can you please check ad0dbb9cdada840abf5040686677af40ec95c4a2 and confirm you're okay with this?

Thanks again!

**Comment by znerol** [comment]
Perfect! Thanks a lot.
