### ISSUE TITLE
Add support for forwarding via SMTP (with SRS due SPF)

### ISSUE THREAD

**Issue by hz61p1** [albertito/chasquid#6]

**Comment by albertito** [comment]
Hi!

Can you elaborate on this?

chasquid already supports forwarding with SRS. If you alias to a non-local domain, then SMTP forwarding with SRS will be used.

**Comment by hz61p1** [comment]
Thanks for the details. The documentation does not explicitly indicate which mechanism is used for this.

**Comment by albertito** [comment]
I see! I can fix that, thanks for pointing it out.

I'll leave this open to track the documentation improvement.

**Comment by albertito** [comment]
Commit 65afb02c adds a paragraph about this in the aliases documentation.

Thanks for the report, and please let me know if you have any suggestion or comment to improve it!
